name: pip_oclock
description: "Pip clock on o'clock"

publish_to: "none"

version: 2.0.2+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  icons_launcher: ^3.0.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^18.0.1
  flutter_foreground_task: ^6.5.0
  provider: ^6.1.1
  timezone: ^0.9.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/

icons_launcher:
  image_path: "assets/pip.png"
  platforms:
    android:
      enable: true
      notification_image: "assets/pip.png"
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: "assets/pip.png"
      adaptive_foreground_image: "assets/pip.png"
      adaptive_round_image: "assets/pip.png"
      adaptive_monochrome_image: "assets/pip.png"
    ios:
      enable: true
